### ISSUE TITLE
"Poem" is two syllables, it reports it as one

### ISSUE THREAD

**Issue by eladavron** [prosegrinder/python-syllables#57]
There may be a bit of debate on this one, but the word `poem` is two syllables and the library only recognizes it as one.

```py
import syllables
print(syllables.estimate("poem"))

# 1
```

Also it thinks `Silence` is 3 syllables

**Comment by davidlday** [comment]
Hi! Thanks for opening this issue. Unfortunately, since this package is meant to estimate I have no way of ensuring the accuracy of specific words. If you need accuracy over speed, consider using  the [cmudict](https://github.com/prosegrinder/python-cmudict) Python library instead.

I use both packages together at times, using `syllables` as a fallback words not in the CMUDict. (see: https://github.com/prosegrinder/python-prosegrinder/blob/main/src/prosegrinder/dictionary.py#L97). Hope this helps!
